node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (D:\CENTRAL_IP\server backend\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (D:\CENTRAL_IP\server backend\node_modules\mysql\lib\Connection.js:94:28)
    at Socket.<anonymous> (D:\CENTRAL_IP\server backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (D:\CENTRAL_IP\server backend\node_modules\mysql\lib\Connection.js:423:8)
    at Protocol.emit (node:events:513:28)
    at Protocol._delegateError (D:\CENTRAL_IP\server backend\node_modules\mysql\lib\protocol\Protocol.js:398:10)
    at Protocol.end (D:\CENTRAL_IP\server backend\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (D:\CENTRAL_IP\server backend\node_modules\mysql\lib\Connection.js:94:28)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}

Node.js v18.16.0
